= FHIRconnect Specification Documentation
:navtitle: Introduction
# :url-asciidoc-lang: https://projects.eclipse.org/projects/technology.asciidoc

== About FHIRconnect

FHIRconnect is a derivative of YAML and a rework of the draft from
Betters https://github.com/better-care[FHIRconnect]. It is used to
bidirectionally map openEHR and FHIR. The aim is to create a mapping
language the communities can use to transform between the standards.
Its aim is to be comprehensive and simple to use, meanwhile trying to
contain all necessary functions for the mappings.

Apart from the transformation the specification and resulting files
should also deal as a documentation of how these things are to be
mapped. So even if vendors do not implement FHIRconnect, they have a
documentation of how this is should be transformed. This is especially
important to maintain a consistency between transforming both standards
throughout institutions.

== Current issues and example mappings

In the repository https://github.com/SevKohler/FHIRconnect?tab=readme-ov-file you can find current issues with the specification under the issue tabs in github.
Also in the directory contained is the library of mappings.
Currently, these contain the mappings for the KDS the german core dataset for research and general archetype mappings.
Be aware that some of the templates are still in rework and some of the templates mapped contain old
bad-quality archetypes created for highmed 8 years ago (org.highmed archetypes) specifically,
we are currently refactoring this.

== DISCLAIMER
FHIRconnect is the result of a research project. To support our research, please cite one of our papers instead of referencing our github in scientific articles. You can find an overview of papers about FHIRconnect here. If you are not sure which paper to cite, we recommend this one:

WIP

Thanks!