= FHIRconnect Specification Documentation
:navtitle: Introduction

== DISCLAIMER

FHIRconnect is the result of a research project.
To support our research, please cite one of our papers instead of referencing our GitHub repository in scientific articles.
You can find an overview of papers about FHIRconnect here.
If you are unsure which paper to cite, we recommend this one:

*WIP*

Thank you!

== About FHIRconnect

FHIRconnect is a mapping specification for bidirectional mapping between openEHR and FHIR. The goal is to create a
mapping language that communities can use to transform data between these standards. The markup language used to express
the mappings is YAML.

FHIRconnect aims to be both comprehensive and simple to use
while providing all necessary functions for mapping.

Beyond transformation, the specification and resulting files should also serve as documentation
on how these mappings should be performed.
Even if vendors do not implement FHIRconnect, they will still have documentation
on how data should be transformed.
This is particularly important for maintaining consistency when mapping both standards across different institutions.

The initial draft of https://github.com/better-care/fhir-connect-mapping-spec[FHIRconnect] was done by https://www.better.care[Better]
, this version is a major overhaul.

The official mapping library of FHIRconnect is maintained
https://github.com/SevKohler/FHIRconnect-mapping-lib/tree/main[here].

== Implementations and Tooling

Two engines run FHIRconnect mappings:

* https://github.com/openfhir/openfhir[openFHIR] (Java). Reference implementation. Both directions,
  REST API, Docker image, public sandbox.
* https://github.com/GinoCanessa/dotnet-fhirconnect[dotnet-fhirconnect] (.NET). Early stage, so far
  only `EVALUATION.vital_status.v1`.

If an engine behaves differently from this specification, the specification wins. Open an issue in
the engine's repository.

Tooling for writing FHIRconnect mappings:


* https://github.com/SevKohler/FHIRconnectTools[FHIRconnectTools]:
** IntelliJ plugin: shows the resolved openEHR and FHIR path of the mapping under the cursor, path
   completion, inspections. Beta. Download from the
   https://github.com/SevKohler/FHIRconnectTools/releases[releases page].
** Claude Code skills: writing and reviewing mapping files (beta), drafting the alignment table before
   writing YAML (alpha), running test data through an engine and fixing the mapping (alpha).
* https://github.com/openFHIR/intellij-fhir-connect[FHIRConnect plugin for IntelliJ] (openFHIR):
  navigation between mappers (Ctrl+click from `slotArchetype`, `slotContext`, `spec.extends` and
  `context.*` to the mapper that declares the name), completion of mapper names, find usages and
  rename across files and more (see official repo). Works in IntelliJ IDEA 2024.2+ and other JetBrains IDEs with the YAML plugin.
  Install from the https://plugins.jetbrains.com/plugin/26927-fhirconnect[JetBrains Marketplace] or
  the https://github.com/openFHIR/intellij-fhir-connect/releases[releases page].

== Current Issues and Example Mappings

You can find current issues related to the specification in the
https://github.com/SevKohler/FHIRconnect-spec[repository] under the "Issues" tab on GitHub.

The repository also contains a library of mappings.
Currently, these include mappings for KDS, the German core dataset for research,
as well as general archetype mappings.

Please note that some templates are still being reworked.
Additionally, some of the mapped templates contain outdated and low-quality archetypes
created for Highmed eight years ago (specifically, the `org.highmed` archetypes).
We are currently in the process of refactoring these.

== Maintaining the Specification

For comments, suggestions, and general discussions,
please use the https://github.com/SevKohler/FHIRconnect-spec[Issues] tab on GitHub.

== Contributors

* Diego Bosca
* Gašper Andrejc
* Severin Kohler
