= DV_CODED_TEXT

Inherits from DV_TEXT.

== CodeableConcept

https://build.fhir.org/datatypes.html#codeableconcept[CodeableConcept]
to https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_coded_text_class[DV_CODED_TEXT].

FHIRconnect engine checks, if the defining_code requires a specific terminology like e.g. SNOMED-CT that
is also contained in the coding. If yes, this one should be transformed into the defining_code instead of the first one.
This can only be done, if both FHIR and openEHR reference the same terminology id for that element.

Otherwise, FHIRconnect transforms the first appearance of coding into the defining_code.
Each further coding is transformed into the term_mappings.


[cols="^1,^1,^1,^2", options="header"]
|===
| FHIRpath        | Comment                                                 | openEHR              | Comment
| coding         | 0..n, either first one or the one with the same terminology_system | defining_code       | 1..1, see xref:types-of-mappings/data-type/CODE_PHRASE.adoc[]
| coding.display | Display of coding of first row                         | defining_code/preferred_term                |
| text          |                                                         | value |
| -             |                                                         | hyperlink            |
| -             |                                                         | formatting           |
| coding        | Each one that was not mapped in defining_code           | mappings             | see xref:types-of-mappings/data-type/TERM_MAPPING.adoc[]
| -             |                                                         | language             |
| -             |                                                         | encoding             |
|===

Example, added a numerator to fever word in order to better identify which one goes where.
[source,json]
----
{
   "_type" : "DV_CODED_TEXT",
    "value" : "Fever1",
    "defining_code" : {
      "_type" : "CODE_PHRASE",
      "terminology_id" : {
        "_type" : "TERMINOLOGY_ID",
        "value" : "http://loinc.org"
      },
      "code_string" : "LP74849-8",
      "preferred_term": "Fever2"
    },
  "mappings": [
    {
      "_type": "TERM_MAPPING",
      "match": "=",
      "target": {
        "_type": "CODE_PHRASE",
        "terminology_id": {
          "_type": "TERMINOLOGY_ID",
          "value": "http://snomed.info/sct"
        },
        "code_string": "386661006",
        "preferred_term": "Fever3"
      }
    }
  ]
}
----

To:
[source,json]
----
"code": {
        "coding":  [
            {
                "system": "http://loinc.org",
                "code": "LP74849-8",
                "display": "Fever2"
            },
            {
                "system": "http://snomed.info/sct",
                "code": "386661006",
                "display": "Fever3"
            }
        ],
      "text": "Fever1"
    },
}
----

== Coding

https://simplifier.net/packages/hl7.fhir.r4.core/4.0.1/files/81979[Coding] to https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_coded_text_class[DV_CODED_TEXT].

[cols="^1,^1,^1,^2", options="header"]
|===
| FHIRpath  | Comment  | openEHR                   | Comment
| system    |         | defining_code/terminology_id/name       |
| version   |         | defining_code/terminology_id/version_id |
| value     |         | defining_code/code_string                |
| display   |         | value                     |
| userSelected |         | -                     |
| -         |         | preferred_term             |
| -         |         | hyperlink                 |
| -         |         | formatting                |
| -         |         | mappings                  |
| -         |         | language                  |
| -         |         | encoding                  |
|===



Example:
[source,json]
----
{
   "_type" : "DV_CODED_TEXT",
    "value" : "Fever",
    "defining_code" : {
      "_type" : "CODE_PHRASE",
      "terminology_id" : {
        "_type" : "TERMINOLOGY_ID",
        "value" : "http://loinc.org"
      },
      "code_string" : "LP74849-8"
    }
}
----

To:
[source,json]
----
"coding":  [
  {
    "system": "http://loinc.org",
    "code": "LP74849-8",
    "display": "Fever"
  }
}
----

