= DV_QUANTITY

== Quantity

https://build.fhir.org/datatypes.html#Quantity[Quantity]
to https://specifications.openehr.org/releases/RM/Release-1.1.0/data_types.html#_dv_quantity_class[DV_QUANTITY].

[cols="^1,^1,^1,^2", options="header"]
|===
| FHIRpath  | Comment  | openEHR                  | Comment
| value    |         | magnitude       | Is a mandatory field in openEHR, whereas not in FHIR.
|    |         | precision |
| code (if exists, else unit)    |         | units               | Is a mandatory field in openEHR, whereas not in FHIR.
| system   |         | units_system                     |
| system         |         | units_display_name            |
| -         |         | normal_range                 |
| -         |         | other_reference_ranges                |
|===

== Integer (or primitive of other kind, i.e. string)

https://build.fhir.org/datatypes.html#integer[Integer]
to https://specifications.openehr.org/releases/RM/Release-1.1.0/data_types.html#_dv_quantity_class[DV_QUANTITY].

[cols="^1,^1,^1,^2", options="header"]
|===
| FHIRpath  | Comment  | openEHR                  | Comment
| value    |         | magnitude       |
|    |         | precision |
|      |         | units               | as its required in openEHR, this needs to be hardcoded to "1" when mapping from FHIR->openEHR
|    |         | units_system                     |
| -         |         | units_display_name            |
| -         |         | normal_range                 |
| -         |         | other_reference_ranges                |
|===

== Ratio

https://build.fhir.org/datatypes.html#Ratio[Ratio]
to https://specifications.openehr.org/releases/RM/Release-1.1.0/data_types.html#_dv_quantity_class[DV_QUANTITY].

`Ratio.numerator` should be used and then it's a Quantity to DV_QUANTITY mapping described above.

== Range

https://build.fhir.org/datatypes.html#Range[Range]
to https://specifications.openehr.org/releases/RM/Release-1.1.0/data_types.html#_dv_quantity_class[DV_QUANTITY].

As range has a 'low' and a 'high' in FHIR, data mappings should pin-point exactly which limit should be
mapped to DV_QUANTITY. If mapping doesn't pin-point to the exact data element, nothing should be mapped to prevent
wrong mapping.
