= DV_TEXT

== String
https://hl7.org/fhir/R4/datatypes.html#string[String] to https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_text_class[DV_TEXT]

The transformation is lacking here a good mapping to FHIR.
String is the one that comes closest.

[cols="^1,^1,^1,^2", options="header"]
|===
| FHIRpath  | comment  | opeEHR | comment
| value |    |  value |
| -  |    |  hyperlink |
| -  |    |  formatting |
| -  |    |  mappings |
| -  |    |  language |
| -  |   |  encoding |

|===

== Coding
https://simplifier.net/packages/hl7.fhir.r4.core/4.0.1/files/81979[Coding] to
https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_text_class[DV_TEXT]
In openEHR each `DV_TEXT` can be annotated with codings using mappings. This we can use to
faithfully transform the FHIR `codings` bidirectionally.

[cols="^1,^1,^1,^2", options="header"]
|===
| FHIRpath  | comment  | opeEHR | comment
| display   |      |  value     |
| -         |      |  hyperlink  |
| -         |      |  formatting|
| coding    |      |  mappings | see <<types-of-mappings/data-type/TERM_MAPPING.adoc#term_mapping, TERM_MAPPING>>
| -         |      |  language |
| -         |      |  encoding |
|===

== CodeableConcept
https://hl7.org/fhir/R4/datatypes.html#codeableconcept[CodeableConcept] to
https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_text_class[DV_TEXT]

In openEHR each `DV_TEXT` can be annotated with codings using mappings.
This we can use to faithfully transform the FHIR `CodeableConcept` bidirectionally.

[cols="^1,^1,^1,^2", options="header"]
|===
| FHIRpath  | comment  | opeEHR | comment
| text      |      |  value     |
| -         |      |  hyperlink  |
| -         |      |  formatting|
| coding    |      |  mappings | see <<types-of-mappings/data-type/TERM_MAPPING.adoc#term_mapping, TERM_MAPPING>>, is also 0..n therfore, can store all codings
| -         |      |  language |
| -         |      |  encoding |
|===