= String

== Coding
https://specifications.openehr.org/releases/BASE/latest/foundation_types.html#_string_class[String] to
https://hl7.org/fhir/R4/datatypes.html#Coding[Coding]

The transformation into a string is lackluster when coming from a coded value. To maintain some of the content, the
coding should be parsed into the String and back as `system::code`, e.g., `http://loinc.org::LP74849-8`. This way,
the most important fields are contained. The double colon (::) is introduced since it represents a unique combination
that rarely appears in text.

[WARNING]
====
When converting back, this may cause problems. Providers need to ensure that the freetext
elements do not contain a `::` or even skip the back-transformation of `::`.
====

[cols="^1,^1,^2,^1,^1,^2", options="header"]
|===
| FHIRpath        | Cardinality | Comment                      | openEHR   | Cardinality       | Comment
| code            | 0..1|               | string   | 1..1                  | openEHR->FHIR
| `system::code`  | 0..1 |   FHIR->openEHR | string   | 1..1                 |  openEHR-> FHIR if contains `::`
| version         | 0..1|                      | -        | -                     |
| display         | 0..1|                      | -        | -                     |
| userSelected    | 0..1|                      | -        | -                     |
|===


[[Identifier]]
== Identifier
https://hl7.org/fhir/R4/datatypes.html#Identifier[Identifier] to
https://specifications.openehr.org/releases/BASE/latest/foundation_types.html#_string_class[String]

The transformation into a string is lackluster when coming from an identifier. To maintain some information, the identifier
uses a double colon (::) since it represents a unique combination that rarely appears in text, similar to the above.

[WARNING]
====
When converting back, this may cause problems. Providers need to ensure that the identifier elements do not contain a
:: or even skip the back-transformation of `::`.
====

[cols="^1,^1,^2,^1,^1,^2", options="header"]
|===
| FHIRpath         | Cardinality | Comment                                             | openEHR   | Cardinality | Comment
| identifier.value | 0..1               |                                                  | string    | 1..1                  | openEHR->FHIR
| identifier       | 0..1               |  FHIR->openEHR encoded as identifier.system:: identifier.value    | string    | 1..1    | openEHR-> FHIR if contains `::`
| use              | 0..1               |                                                  | -        | -                     |
| type             | 0..1               |                                                  | -        | -                     |
| system           | 0..1               |                                                  | -        | -                     |
| value            | 0..1               |                                                  | -        | -                     |
| period           | 0..1               |                                                  | -        | -                     |
|===




== References
https://specifications.openehr.org/releases/BASE/latest/foundation_types.html#_string_class[String] to
https://hl7.org/fhir/R4/references.html#Reference[Reference]

[NOTE]
====
It is recommended to resolve non-clinical data
references using the demographics see
<<types-of-mappings/data-type/FHIRReference.adoc#ReferencesDemographics, FHIRReferences>>
.
====

The transformation into a string is lackluster when coming from a reference. The reference has three ways of representation in FHIR,
listed below.

=== Identifier contained
In case the FHIR reference contains a direct identifier, see <<Identifier>>.

This is the transformation to be used for reference as a *default* if other fields are provided in the FHIR reference
or when transforming from openEHR to FHIR.

=== Reference contained
In case the reference URL is contained, but no identifier is provided, nor is the reference resolvable as part of
the Bundle or via a GET to the FHIR server sending it. Copying over the reference string is better than copying over nothing.

[WARNING]
====
Providers have to decide if they accept this sort of encoding as part of their platform.
====

[cols="^1,^1,^2,^1,^1,^2", options="header"]
|===
| FHIRpath   | Cardinality | Comment  | openEHR   | Cardinality | Comment
| reference  | 0..1               |          | string    | 1..1                  |
| type       | 0..1               |          | -        | -                     |
| identifier | 0..1               |          | -        | -                     |
| display    | 0..1               |          | -        | -                     |
|===


=== Reference contained and resolvable
In case the reference URL is contained and resolvable due to it being contained in the Bundle or via GET. The
identifier is to be accessed as part of this reference, therefore being a <<Identifier, Identifier to String>> transformation.
