= Slot Archetypes
:navtitle: SlotArchetypes

To facilitate the strength of openEHR, also as part of the mappings, the slotArchetypes were introduced. These allow us
to link other mappings. This enables us to reuse existing mappings and split the logic for transformation into smaller,
better-maintained files.

The `slotArchetype` is always called by the name of the mapping contained in the header.
As previous examples:

[source,yaml]
----
grammar: FHIRConnect/v0.0.1
type: model
metadata:
  name: CLUSTER.lebensphase.v0
  version: 1.0.0
spec:
  system: FHIR
  version: R4
  openEhrConfig:
    archetype: openEHR-EHR-CLUSTER.lebensphase.v0
----

Therefore, the slotArchetype must point to `CLUSTER.lebensphase.v0`.

[source,yaml]
----
mappings:
  - name: "period"
    mappings:
      - name: "start"
        with:
          fhir: "$resource.onset.as(Period).start"
          openehr: "items[at0077]"
      - name: "lebensphaseCluster"
        with:
          fhir: "$resource.onset.as(Period)"
          openehr: "$archetype/data[at0001]/items[openEHR-EHR-CLUSTER.lebensphase.v0]"
        slotArchetype: "CLUSTER.lebensphase.v0"
----

This will redirect the mapping to the mapping file that contains the mapping definition (in the example the lebensphase mapping) and execute the transformation
there. The path to which this mapping is transformed is specified in the openehr attribute (`openehr: "$archetype/data[at0001]/items[openEHR-EHR-CLUSTER.lebensphase.v0]"` in the example).
The paths contained in the `with:` are not automatically transformed as they would normally do, since this logic is contained
in the slotArchetype.
