= Data mapping types
:navtitle: Data mapping types

Mappings between two data values are executed depending on the data type of the element.
As an example if a period is provided FHIRconnect maps this period to an interval in the corresponding
path in openEHR, if it's a valid data type.

If no valid data-type is provided these could be transformed into another element e.g. the period start into a
DV_DATE_TIME. This is up to vendors how strict or relaxed they want to design their engine.

== DV_TEXT
The transformation is lacking here a good mapping to FHIR.
String is the one that comes closest:

https://simplifier.net/packages/hl7.fhir.r4.core/4.0.1/files/81888[String] to https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_text_class[DV_TEXT]

[cols="^1,^1,^1,^2", options="header"]
|===
| FHIRpath  | comment  | opeEHR | comment
| value |    |  value |
| -  |    |  hyperlink |
| -  |    |  formatting |
| -  |    |  mappings |
| -  |    |  language |
| -  |   |  encoding |

|===


== DV_CODED_TEXT
[[CodeableConcept]]
=== CodeableConcept

https://simplifier.net/packages/hl7.fhir.r4.core/4.0.1/files/83219[CodeableConcept]
to https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_coded_text_class[DV_CODED_TEXT].

FHIRconnect engine checks, if the defining_code requires a specific terminology like e.g. SNOMED-CT that
is also contained in the coding. If yes, this one should be transformed into the defining_code instead of the first one.
This can only be done, if both FHIR and openEHR reference the same terminology id for that element.

Otherwise, FHIRconnect transforms the first appearance of coding into the defining_code.
Each further coding is transformed into the term_mappings.


[cols="^1,^1,^1,^2", options="header"]
|===
| FHIRpath        | Comment                                                 | openEHR              | Comment
| coding         | 0..n, either first one or the one with the same terminology_system | defining_code       | 1..1, see <<CODE_PHRASE>>
| coding.display | Display of coding of first row                          | value                |
| text          |                                                         | defining_code/preferred_term | Is added to the defining_code preferred_term
| -             |                                                         | hyperlink            |
| -             |                                                         | formatting           |
| coding        | Each one that was not mapped in defining_code            | mappings             | See <<TERM_MAPPING>>
| -             |                                                         | language             |
| -             |                                                         | encoding             |
|===

Example:
[source,json]
----
{
   "_type" : "DV_CODED_TEXT",
    "value" : "Fever",
    "defining_code" : {
      "_type" : "CODE_PHRASE",
      "terminology_id" : {
        "_type" : "TERMINOLOGY_ID",
        "value" : "http://loinc.org"
      },
      "code_string" : "LP74849-8",
      "preferred_term": "Fever"
    },
  "mappings": [
    {
      "_type": "TERM_MAPPING",
      "match": "=",
      "target": {
        "_type": "CODE_PHRASE",
        "terminology_id": {
          "_type": "TERMINOLOGY_ID",
          "value": "http://snomed.info/sct"
        },
        "code_string": "386661006"
      }
    }
  ]
}
----

To:
[source,json]
----
"code": {
        "coding":  [
            {
                "system": "http://loinc.org",
                "code": "LP74849-8",
                "display": "Fever"
            },
            {
                "system": "http://snomed.info/sct",
                "code": "386661006",
                "display": "Fever"
            }
        ],
      "text": "Fever"
    },
}
----

=== Coding

https://simplifier.net/packages/hl7.fhir.r4.core/4.0.1/files/81979[Coding] to https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_coded_text_class[DV_CODED_TEXT].

[cols="^1,^1,^1,^2", options="header"]
|===
| FHIRpath  | Comment  | openEHR                   | Comment
| system    |         | defining_code/terminology_id/name       |
| version   |         | defining_code/terminology_id/version_id |
| value     |         | defining_code/code_string                |
| display   |         | value                     |
| userSelected |         | -                     |
| -         |         | preferred_term             |
| -         |         | hyperlink                 |
| -         |         | formatting                |
| -         |         | mappings                  |
| -         |         | language                  |
| -         |         | encoding                  |
|===



Example:
[source,json]
----
{
   "_type" : "DV_CODED_TEXT",
    "value" : "Fever",
    "defining_code" : {
      "_type" : "CODE_PHRASE",
      "terminology_id" : {
        "_type" : "TERMINOLOGY_ID",
        "value" : "http://loinc.org"
      },
      "code_string" : "LP74849-8"
    }
}
----

To:
[source,json]
----
"coding":  [
  {
    "system": "http://loinc.org",
    "code": "LP74849-8",
    "display": "Fever"
  }
}
----

[[CODE_PHRASE]]
== CODE_PHRASE
https://simplifier.net/packages/hl7.fhir.r4.core/4.0.1/files/81979[Coding] to https://specifications.openehr.org/releases/RM/latest/data_types.html#_code_phrase_class[CODE_PHRASE]
[cols="^1,^1,^1,^2", options="header"]
|===
| FHIRpath  | Comment  | openEHR                  | Comment
| system    |         | terminology_id/name       |
| version   |         | terminology_id/version_id |
| value     |         | code_string               |
| display   |         | value                     |
| userSelected |      | -                         |
| -         |         | preferred_term            |
| -         |         | hyperlink                 |
| -         |         | formatting                |
| -         |         | mappings                  |
| -         |         | language                  |
| -         |         | encoding                  |
|===

Example:
[source,json]
----
{
    "defining_code" : {
      "_type" : "CODE_PHRASE",
      "terminology_id" : {
        "_type" : "TERMINOLOGY_ID",
        "value" : "http://loinc.org"
      },
      "code_string" : "LP74849-8"
    }
}
----

To:
[source,json]
----
"coding":  [
  {
    "system": "http://loinc.org",
    "code": "LP74849-8",
    "display": "Fever"
  }
}
----

[[TERM_MAPPING]]
== TERM_MAPPING
For context see <<CodeableConcept>>

https://specifications.openehr.org/releases/RM/latest/data_types.html#_term_mapping_class[TERM_MAPPING] to
https://simplifier.net/packages/hl7.fhir.r4.core/4.0.1/files/81979[Coding]

[cols="^1,^1,^1,^2", options="header"]
|===
| FHIRpath  | Comment  | openEHR  | Comment
| -         |         | match    | hard coded to `=`, other operators not mappable to FHIR
| -         |         | purpose  |
| coding    |         | target   | see <<CODE_PHRASE>>
|===
Example:
[source,json]
----
{
  "mappings": [
    {
      "_type": "TERM_MAPPING",
      "match": "=",
      "target": {
        "_type": "CODE_PHRASE",
        "terminology_id": {
          "_type": "TERMINOLOGY_ID",
          "value": "http://snomed.info/sct"
        },
        "code_string": "386661006"
      }
    }
  ]
}
----

To:
[source,json]
----
"coding":  [
  {
    "system": "http://loinc.org",
    "code": "LP74849-8",
    "display": "Fever"
  }
}
----


== DV_PARAGRAPH


== DV_ORDERED


== DV_INTERVAL


== REFERENCE_RANGE


== DV_ORDINAL


== DV_SCALE


== DV_QUANTIFIED


== DV_AMOUNT


== DV_QUANTITY


== DV_COUNT


== DV_PROPORTION


== DV_ABSOLUTE_QUANTITY


== DV_TEMPORAL


== DV_DATE


== DV_TIME


== DV_DATE_TIME


== DV_DURATION


== DV_ENCAPSULATED


== DV_MULTIMEDIA


== DV_PARSABLE


== DV_URI


== DV_EHR_URI



`DV_IDENTIFIER`: type, type system `+` `::` `+` value, value assigner, assigner ?




== Deprecated
This is the old way (v0.9) of mapping using static types, since the information is derivable from
the instances of FHIR and openEHR this static typing is deprecated. It  creates more mapping
fields and makes users required to map each field possible in a data type manually.

[cols="^1,^1,^1,^2", options="header"]
|===
| Type ID / FHIR  | openEHR       | Primitive | "FLAT / FHIR" Attributes Pairs
| QUANTITY        | DV_QUANTITY   | true      | magnitude / value, unit / unit
| QUANTITY        | DV_ORDINAL    | true      | ordinal / value, value / unit,  code / code
| QUANTITY        | DV_COUNT      | true      | (direct)
| DATETIME        | DV_DATE_TIME  | true      | (direct)
| CODEABLECONCEPT | DV_CODED_TEXT | false     | *nested* / coding, value / text
| CODING          | CODE_PHRASE   | true      | code / code, terminology / system
| STRING          | DV_TEXT       | true      | (direct)
| DOSAGE          | NONE          | false     | (special)
|===

