= Data mapping types
:navtitle: Data mapping types

Mappings between two data values are executed depending on the data type of the element.
As an example if a period is provided FHIRconnect maps this period to an interval in the corresponding
path in openEHR, if its a valid data type.

If no valid data-type is provided
Data mapping types are not mandatory in FHIRconnect, since the corresponding mapping is resolved by the
types contained in the serialized FHIR instances and openEHR compositions.

This chapter is mainly used to describe how these mappings are to be processed.

https://build.fhir.org/datatypes.html


https://simplifier.net/packages/hl7.fhir.r4.core/4.0.1/files/81701
https://specifications.openehr.org/releases/UML/development/index.html#Architecture___18_1_83e026d_1433773263991_74683_5958


https://specifications.openehr.org/releases/RM/Release-1.1.0/data_types.html#_data_types_information_model
Maybe we should list this as it should be transformed by data types:

State that this depends on the input type, here we just introduce the easiest fits

using openEHR types since started with


== DV_TEXT
String

== TERM_MAPPING


== CODE_PHRASE


== DV_CODED_TEXT


== DV_PARAGRAPH


== DV_ORDERED


== DV_INTERVAL


== REFERENCE_RANGE


== DV_ORDINAL


== DV_SCALE


== DV_QUANTIFIED


== DV_AMOUNT


== DV_QUANTITY


== DV_COUNT


== DV_PROPORTION


== DV_ABSOLUTE_QUANTITY


== DV_TEMPORAL


== DV_DATE


== DV_TIME


== DV_DATE_TIME


== DV_DURATION


== DV_ENCAPSULATED


== DV_MULTIMEDIA


== DV_PARSABLE


== DV_URI


== DV_EHR_URI



`DV_IDENTIFIER`: type, type system `+` `::` `+` value, value assigner, assigner ?




== Deprecated
This is the old way (v0.9) of mapping using static types, since the information is derivable from
the instances of FHIR and openEHR this static typing is deprecated. It  creates more mapping
fields and makes users required to map each field possible in a data type manually.

[cols="^1,^1,^1,^2", options="header"]
|===
| Type ID / FHIR  | openEHR       | Primitive | "FLAT / FHIR" Attributes Pairs
| QUANTITY        | DV_QUANTITY   | true      | magnitude / value +<br> unit / unit
| QUANTITY        | DV_ORDINAL    | true      | ordinal / value +<br> value / unit +<br> code / code
| QUANTITY        | DV_COUNT      | true      | (direct)
| DATETIME        | DV_DATE_TIME  | true      | (direct)
| CODEABLECONCEPT | DV_CODED_TEXT | false     | *nested* / coding +<br> value / text
| CODING          | CODE_PHRASE   | true      | code / code +<br> terminology / system
| STRING          | DV_TEXT       | true      | (direct)
| DOSAGE          | NONE          | false     | (special)
|===

