= Data mapping types
:navtitle: Data mapping types

Mappings between two data values are executed depending on the data type of the element.
As an example if a period is provided FHIRconnect maps this period to an interval in the corresponding
path in openEHR, if its a valid data type.

If no valid data-type is provided
Data mapping types are not mandatory in FHIRconnect, since the corresponding mapping is resolved by the
types contained in the serialized FHIR instances and openEHR compositions.

This chapter is mainly used to describe how these mappings are to be processed.

https://build.fhir.org/datatypes.html


https://simplifier.net/packages/hl7.fhir.r4.core/4.0.1/files/81701
https://specifications.openehr.org/releases/UML/development/index.html#Architecture___18_1_83e026d_1433773263991_74683_5958


https://specifications.openehr.org/releases/RM/Release-1.1.0/data_types.html#_data_types_information_model
Maybe we should list this as it should be transformed by data types:

State that this depends on the input type, here we just introduce the easiest fits

using openEHR types since started with


== DV_TEXT
The transformation is lacking here a good mapping to FHIR.
String is the one that comes closest:

https://simplifier.net/packages/hl7.fhir.r4.core/4.0.1/files/81888[String] to https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_text_class[DV_TEXT]

[cols="^1,^1,^1,^2", options="header"]
|===
| FHIRpath  | comment  | opeEHR | comment
| value |    |  value |
| -  |    |  hyperlink |
| -  |    |  formatting |
| -  |    |  mappings |
| -  |    |  language |
| -  |   |  encoding |

|===


== DV_CODED_TEXT
https://simplifier.net/packages/hl7.fhir.r4.core/4.0.1/files/83219[CodeableConcept]
to https://specifications.openehr.org/releases/RM/latest/data_types.html#_dv_coded_text_class[DV_CODED_TEXT].

FHIRconnect engine checks, if the defining_code requires a specific terminology like e.g. SNOMED-CT that
is also contained in the coding. If yes, this one should be transformed into the defining_code instead of the first one.
This can only be done, if both FHIR and openEHR reference the same terminology id for that element.

Otherwise, FHIRconnect transforms the first appearance of coding into the defining_code.
Each further coding is transformed into the term_mappings.


[cols="^1,^1,^1,^2", options="header"]
|===
| FHIRpath  | comment  | openEHR | comment
|coding | 0..n, either first one or the one with the same terminology_system  |  defining_code | 1..1, see <<CODE_PHRASE>>
| text |     |  defining_code/preferred_term | is added to the defining_code preferred_term
| -     |    |  hyperlink   |
| -     |    |  formatting  |
| coding| each one that was not mapped in defining_code   |  mappings    | see <<TERM_MAPPING>>
| -     |    |  language    |
| -     |    |  encoding    |
|===

Example:
[source,json]
----
{
   "_type" : "DV_CODED_TEXT",
    "value" : "fever",
    "defining_code" : {
      "_type" : "CODE_PHRASE",
      "terminology_id" : {
        "_type" : "TERMINOLOGY_ID",
        "value" : "http://loinc.org"
      },
      "code_string" : "LP74849-8",
       "preferred_term": "Fever"
    },
  "mappings": [
    {
      "_type": "TERM_MAPPING",
      "match": "=",
      "purpose": "multiple_coding",
      "target": {
        "_type": "CODE_PHRASE",
        "terminology_id": {
          "_type": "TERMINOLOGY_ID",
          "value": "http://snomed.info/sct"
        },
        "code_string": "386661006"
      }
    }
  ]
}
----

To:
[source,json]
----
"code": {
        "coding":  [
            {
                "system": "http://loinc.org",
                "code": "LP74849-8",
                "display": "Fever"
            },
            {
                "system": "http://snomed.info/sct",
                "code": "386661006",
                "display": "Fever"
            }
        ],
      "text": "Fever"
    },
}
----


[[CODE_PHRASE]]
== CODE_PHRASE

[cols="^1,^1,^1,^2", options="header"]
|===
| FHIRpath  | comment  | opeEHR | comment
| value |    |  value |
| -  |    |  hyperlink |
| -  |    |  formatting |
| -  |    |  mappings |
| -  |    |  language |
| -  |   |  encoding |

|===

[[TERM_MAPPING]]
== TERM_MAPPING

use match `=` purpose multi_coding
target easy


== DV_PARAGRAPH


== DV_ORDERED


== DV_INTERVAL


== REFERENCE_RANGE


== DV_ORDINAL


== DV_SCALE


== DV_QUANTIFIED


== DV_AMOUNT


== DV_QUANTITY


== DV_COUNT


== DV_PROPORTION


== DV_ABSOLUTE_QUANTITY


== DV_TEMPORAL


== DV_DATE


== DV_TIME


== DV_DATE_TIME


== DV_DURATION


== DV_ENCAPSULATED


== DV_MULTIMEDIA


== DV_PARSABLE


== DV_URI


== DV_EHR_URI



`DV_IDENTIFIER`: type, type system `+` `::` `+` value, value assigner, assigner ?




== Deprecated
This is the old way (v0.9) of mapping using static types, since the information is derivable from
the instances of FHIR and openEHR this static typing is deprecated. It  creates more mapping
fields and makes users required to map each field possible in a data type manually.

[cols="^1,^1,^1,^2", options="header"]
|===
| Type ID / FHIR  | openEHR       | Primitive | "FLAT / FHIR" Attributes Pairs
| QUANTITY        | DV_QUANTITY   | true      | magnitude / value +<br> unit / unit
| QUANTITY        | DV_ORDINAL    | true      | ordinal / value +<br> value / unit +<br> code / code
| QUANTITY        | DV_COUNT      | true      | (direct)
| DATETIME        | DV_DATE_TIME  | true      | (direct)
| CODEABLECONCEPT | DV_CODED_TEXT | false     | *nested* / coding +<br> value / text
| CODING          | CODE_PHRASE   | true      | code / code +<br> terminology / system
| STRING          | DV_TEXT       | true      | (direct)
| DOSAGE          | NONE          | false     | (special)
|===

