= FollowedBy
:navtitle: FollowedBy

FHIRConnect follows a top-down approach combined with iterating and accessing paths to execute logic
that aligns with child elements. To facilitate this, `FollowedBy` was introduced. 
The `FollowedBy` mechanism allows to attach mappings to each other, ensuring their execution occurs as the next step
after the parent mapping method has been executed.

The reason for this is that there are nested paths in FHIR and openEHR.
For `0..n` root elements, mappings must be executed `0..n` times.
To execute a mapping for two different child nodes within this path, the `with` logic is not enough. If we split this into two separate `with` mappings, they will overwrite each
other since both address the same root path.

[source,yaml]
----
mappings:
  - name: "period"
    with:
      fhir: "$resource.onset.as(Period)"
      openehr: "$archetype/data[at0001]"
      type: "NONE"
    openehrCondition:
      targetRoot: "$archetype/data[at0001]"
      targetAttribute: "items[openEHR-EHR-CLUSTER.lebensphase.v0]"
      operator: "not empty"
    followedBy:
      mappings:
        - name: "start"
          with:
            fhir: "start"
            openehr: "items[at0077]"

        - name: "lebensphaseCluster"
          with:
            fhir: "$fhirRoot"
            openehr: "$archetype/data[at0001]/items[openEHR-EHR-CLUSTER.lebensphase.v0]"
          slotArchetype: "CLUSTER.lebensphase.v0"
----

Here, the onset is accessed if it is a period (FHIRPath helps us here as a shortcut instead of using `fhirCondition`)
and executes a mapping based on the start time of the period. Additionally, we trigger a slot archetype cluster mapping.
Slot archetypes are explained in the next chapter.


If it was writen as two single `with:` statements, the cluster mappings would, when converting openEHR to FHIR,
overwrite the `"start"` mapping since it maps the same path.

[source,yaml]
----
mappings:
  - name: "start"
    with:
      fhir: "$resource.onset.as(Period).start"
      openehr: "items[at0077]"

  - name: "lebensphaseCluster"
    with:
      fhir: "$resource.onset.as(Period)"
      openehr: "$archetype/data[at0001]/items[openEHR-EHR-CLUSTER.lebensphase.v0]"
    slotArchetype: "CLUSTER.lebensphase.v0"
----

== Path construction

All followedBy mappings start with parent's path. In the example above, resolved path used for actual mapping
of `- name: "start""` would be $resource.onset.as(Period).start. First part being from the parent and the `start` being
from the followedBy mapping. In the same manner, openehr paths are concatenated.

In case you do not want a followedBy mapping to include the parent's path, you can always reference `$openehrRoot`, `$archetype`,
`$fhirRoot` or `$resource` (see: xref:basics/Variables.adoc[]).
