= Recurring Elements
:navtitle: Recurrence

When mapping recurring elements, it is crucial to align both FHIR and openEHR data types
at the same level. Otherwise, recurring elements may not function correctly, leading to
data overwriting instead of properly mapping all occurrences.

== Example Mapping

[source,yaml]
----
 mappings:
  - name: "recurring"
    with:
     fhir: "$resource.diagnosis" # 0..n
     openehr: "$archetype/data[at0001]/data[0002]" # 0..n
     type: "NONE"
    followedBy:
      mappings:
        - name: "code"
          with:
            fhir: "use"
            openehr: "/items[at0030]"
        - name: "note"
          with:
            fhir: "rank"
            openehr: "items[at0045]"
----

In the example above, both `diagnosis` and
`$archetype/data[at0001]/data[0002]` are recurring elements (0..n) that map to each other.
Therefore, they are mapped at the same level. Each occurrence of `diagnosis` is mapped within `followedBy`.
This ensures that all diagnosis fields are properly mapped.

== Incorrect Mapping

If the mapping is structured incorrectly, as shown below, each occurrence of `diagnosis` would
overwrite the previous one, resulting in only the last occurrence being mapped:

[source,yaml]
----
 mappings:
  - name: "recurring"
    with:
     fhir: "$resource.diagnosis" # 0..n
     openehr: "$archetype/data[at0001]" # 1..1
     type: "NONE" # do not map just iterate here, since the values are in the paths below
    followedBy:
      mappings:
        - name: "code"
          with:
            fhir: "code"
            openehr: "data[0002]/items[at0030]" #  0..n
        - name: "note"
          with:
            fhir: "note"
            openehr: "data[0002]/items[at0045]"  #  0..n  would overwrite "code", since it write into data[0002
----

This approach mistakenly nests the `code` and `note` mappings directly under `recurring`, causing
each new occurrence to overwrite the previous one instead of maintaining all occurrences.
Furthermore, when mapping back from openEHR into FHIR, there will be only one instance transformed
into `diagnosis`, since `data[at0001]` has just a single occurrence and was used instead of `data[0002]`.
