= Recurring Elements
:navtitle: Recurrence

When mapping recurring elements, it is crucial to align both FHIR and openEHR data types
at the same level. Otherwise, recurring elements may not function correctly, leading to
data overwriting instead of properly mapping all occurrences.

== Example Mapping

[source,yaml]
----
  - name: "specimen"
    extension: "add"
    with:
      fhir: "$resource.specimen" # 0..n
      openehr: "$reference"
      type: "NONE"
    reference:
      resourceType: "Specimen"
      mappings:
        - name: "specimenRecurring"
          with:
            fhir: "$fhirRoot"
#ServiceRequest FHIR Resource has a specimen that is recurring ($fhirRoot in this example
# is parent's specimen)
            openehr: "$archetype/activities[at0001]/description[at0009]/items[openEHR-EHR-CLUSTER.specimen.v1]"
# in openEHR, this item is a recurring element as well
          followedBy:
             mappings:
                   - name: "type"
                     with:
                       fhir: "type"
                       openehr: "items[at0029]"
                   - name: "note"
                     with:
                       fhir: "note.text"
                       openehr: "items[at0045]"
----

In the example above, both `ServiceRequest.specimen` as well
as `$archetype/activities[at0001]/description[at0009]/items[openEHR-EHR-CLUSTER.specimen.v1]` are recurring
elements, therefore they are specified on the same level in the mapping. All mappings of a specific
occurrence of `specimen` are within `followedBy` or would otherwise need to be a
`slotArchetype` mapping. In this way, all specimens are mapped.

== Incorrect Mapping

If contrary, you wrote something like this, you would be overriding the `specimen` with each
occurrence and end up only with the last item being mapped:

[source,yaml]
----
  - name: "specimen"
    extension: "add"
    with:
      fhir: "$resource.specimen" # 0..n
      openehr: "$reference"
      type: "NONE"
    reference:
      resourceType: "Specimen"
      mappings:
        - name: "type"
          with:
            fhir: "$fhirRoot.type"
            openehr: "$archetype/activities[at0001]/description[at0009]/items[openEHR-EHR-CLUSTER.specimen.v1]/items[at0029]"
        - name: "note"
          with:
            fhir: "$fhirRoot.note.text"
            openehr: "$archetype/activities[at0001]/description[at0009]/items[openEHR-EHR-CLUSTER.specimen.v1]/items[at0045]"
----

This approach mistakenly nests the `code` and `note` mappings directly under `recurring`, causing
each new occurrence to overwrite the previous one instead of maintaining all occurrences.
Furthermore, when mapping back from openEHR into FHIR, there will be only one instance transformed
into `diagnosis`, since `data[at0001]` has just a single occurrence and was used instead of `data[0002]`.
