= Recurring Elements
:navtitle: Recurrence

When mapping recurring elements, it is crucial to align both FHIR and openEHR data types
at the same level. Otherwise, recurring elements may not function correctly, leading to
data overwriting instead of properly mapping all occurrences.

== Example Mapping

[source,yaml]
----
  - name: "specimen"
    with:
      fhir: "$resource.specimen" # 0..n
      openehr: "$reference"
      type: "NONE"
    reference:
      resourceType: "Specimen"
      mappings:
        - name: "specimenRecurring"
          with:
#ServiceRequest FHIR Resource has a specimen that is recurring
            fhir: "$fhirRoot"
# in openEHR, this item is a recurring element as well
            openehr: "$archetype/activities[at0001]/description[at0009]/items[openEHR-EHR-CLUSTER.specimen.v1]" # 0..n
          followedBy:
             mappings:
                   - name: "type"
                     with:
                       fhir: "type"
                       openehr: "items[at0029]"
                   - name: "note"
                     with:
                       fhir: "note.text"
                       openehr: "items[at0045]"
----

In the example above, both `ServiceRequest.specimen` as well
as `$archetype/activities[at0001]/description[at0009]/items[openEHR-EHR-CLUSTER.specimen.v1]` are recurring
elements, therefore they are specified on the same level in the mapping. All mappings of a specific
occurrence of `specimen` are within `followedBy` (correct would be the use of a
`slotArchetype` mapping, for example purpose left out). For each specimen one cluster is created.
Each of which maps in the `followedBy` the elements of the cluster.

== Incorrect Mapping

If contrary, this would be overriding the `specimen` with each
occurrence and end up only with the last item being mapped. It creates a new `specimen` for each specimen contained.
It does map this only to one appearance in the cluster. Therefore, only the last specimen is transformed.
Each `note` and `type` method overwrites the predecessor one.

[source,yaml]
----
  - name: "specimen"
    with:
      fhir: "$resource.specimen" # 0..n
      openehr: "$reference"
      type: "NONE"
    reference:
      resourceType: "Specimen"
      mappings:
        - name: "type"
          with:
            fhir: "$fhirRoot.type"
            openehr: "$archetype/activities[at0001]/description[at0009]/items[openEHR-EHR-CLUSTER.specimen.v1]/items[at0029]"
        - name: "note"
          with:
            fhir: "$fhirRoot.note.text"
            openehr: "$archetype/activities[at0001]/description[at0009]/items[openEHR-EHR-CLUSTER.specimen.v1]/items[at0045]"
----
